gitSync:
  enabled: true
  env:
  - name: GITSYNC_REPO
    value: https://github.com/akfmdl/mlops-lifecycle.git
  - name: GITSYNC_REF
    value: main
  image: registry.k8s.io/git-sync/git-sync:v4.3.0
  subPath: model_repository
tritonServers:
- args:
  - tritonserver
  - --model-repository=/git/mlops-lifecycle.git/model_repository
  - --model-control-mode=explicit
  - --load-model=onnx-model
  env:
  - name: MLFLOW_TRACKING_URI
    value: http://mlflow-tracking.mlops-platform.svc.cluster.local:80
  - name: MLFLOW_MODEL_NAME
    value: yolo11n-onnx
  - name: MLFLOW_MODEL_VERSION
    value: '1'
  - name: CUDA_VISIBLE_DEVICES
    value: ''
  image: goranidocker/tritonserver:python-v1
  name: onnx-model
  replicas: 1
  service:
    type: NodePort
