{{- if .Values.nvidia.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  labels:
    app: nvidia-device-plugin
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      priorityClassName: "system-node-critical"
      tolerations:
        {{- toYaml .Values.nvidia.tolerations | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nvidia.nodeSelector | nindent 8 }}
      containers:
      - name: nvidia-device-plugin-ctr
        image: "{{ .Values.nvidia.image.repository }}:{{ .Values.nvidia.image.tag }}"
        imagePullPolicy: {{ .Values.nvidia.image.pullPolicy }}
        env:
          - name: FAIL_ON_INIT_ERROR
            value: "false"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
{{- end }} 