{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apiserver.fullname" . }}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  {{- with .Values.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.pvc.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
{{- end }}