{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiserver.fullname" . }}-node-reader
rules:
- apiGroups: ["*"]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiserver.fullname" . }}-deployment-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apiserver.fullname" . }}-node-reader
subjects:
- kind: ServiceAccount
  name: {{ include "apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "apiserver.fullname" . }}-node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apiserver.fullname" . }}-deployment-reader
subjects:
- kind: ServiceAccount
  name: {{ include "apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "apiserver.fullname" . }}-deployment-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}