{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "apiserver.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.prefix }}
    route:
    - destination:
        host: {{ include "apiserver.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
