{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "trace_id", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_requests_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_exceptions_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"}"
    }
   ]
  },
  {
   "title": "Requests Average Duration(ms)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_duration_seconds_sum{app_name=\"$app_name\", path=~\".*/predict|.*/models\"} / fastapi_requests_duration_seconds_count{app_name=\"$app_name\", path=~\".*/predict|.*/models\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"$app_name\", status_code=~\"2.*\", path=~\".*/predict|.*/models\"}) / sum by(path) (fastapi_responses_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"$app_name\", status_code=~\"5.*\", path=~\".*/predict|.*/models\"}) / sum by(path) (fastapi_responses_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "fastapi_requests_in_progress{app_name=\"$app_name\", path=~\".*/predict|.*/models\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total{app_name=\"$app_name\", path=~\".*/predict|.*/models\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CRITICAL | ERROR | FATAL Logs of Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\".*fastapi-app\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>]` | type=~\"CRITICAL|ERROR|FATAL\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CRITICAL | ERROR | FATAL Logs of FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "{compose_service=~\".*fastapi-app\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>]` | type=~\"CRITICAL|ERROR|FATAL\""
    }
   ]
  },
  {
   "title": "WARN | INFO Logs of Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\".*fastapi-app\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>]` | type=~\"WARN|INFO\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "WARN | INFO Logs of FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "{compose_service=~\".*fastapi-app\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>]` | type=~\"WARN|INFO\""
    }
   ]
  }
 ]
}