name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "dags/Dockerfile"
      - "dags/requirements.txt"

env:
  HARBOR_REGISTRY: harbor-registry.mlops-platform.svc.cluster.local
  HARBOR_USERNAME: admin
  HARBOR_PASSWORD: admin
  IMAGE_NAME: ${{ github.repository }}-airflow

jobs:
  build-and-push:
    runs-on: mlops-lifecycle-runner-scale-set
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ env.HARBOR_USERNAME }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dags
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install yq
        run: |
          echo "Installing yq..."
          wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update K8S_DAG_IMAGE in values.yaml
        run: |
          # Find and update the K8S_DAG_IMAGE in the airflow.env array
          yq -i '.airflow.env |= map(if .name == "K8S_DAG_IMAGE" then .value = "${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" else . end)' charts/mlops-platform/values.yaml

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add charts/mlops-platform/values.yaml
          git commit -m "Update K8S_DAG_IMAGE to ${{ github.sha }}"
          git push
